MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.feeds import AllArticlesRssFeed


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace = 'blog')),
    path('', include('comments.urls', namespace = 'comments')),
    path('all/rss/', AllArticlesRssFeed(), name = 'rss'),
    path('search/', include('haystack.urls')),


]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('article/<int:pk>/', views.ArticlePageView.as_view(), name = 'article_page'),
    path('archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name = 'archives'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name = 'category'),
    path('tag/<int:pk>/', views.TagView.as_view(), name = 'tag'),
    path('about/', views.about_page, name = 'about'),
    path('contact/', views.contact_page, name = 'contact'),
    # path('search/', views.search, name = 'search'),


]

comments/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'comments'

urlpatterns = [
    # path('comment/article/<int:article_id>/', views.article_comment, name = 'article_comment'),
    url(r'^comment/article/(?P<article_id>[0-9]+)/$', views.article_comment, name = 'article_comment'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags
import markdown


# Create your models here.

# class name represent table name in database
class Category(models.Model):
    name = models.CharField(max_length = 30)
    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length = 30)
    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(default = 'Title', max_length = 30)
    content = models.TextField(null = True)
    create_time = models.DateTimeField(auto_now_add = True)
    modify_time = models.DateTimeField(auto_now = True)
    summary = models.CharField(max_length = 200, blank = True)
    category = models.ForeignKey(Category, on_delete = models.CASCADE)  # 级联
    tags = models.ManyToManyField(Tag, blank = True)
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    views = models.PositiveIntegerField(default = 0, editable = False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article_page', kwargs = {'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields = ['views'])

    def save(self, *args, **kwargs):
        if not self.summary:
            md = markdown.Markdown(extensions = [
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.summary = strip_tags(md.convert(self.content))[:50]

        super(Article, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-create_time']

comments/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length = 30)
    email = models.EmailField(max_length = 100)
    url = models.URLField(blank = True)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add = True)
    article = models.ForeignKey('blog.Article', on_delete = models.CASCADE)

    def __str__(self):
        return self.text[:20]

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Article, Category, Tag
from comments.forms import CommentForm
from django.views.generic import ListView, DetailView
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
from django.db.models import Q

import markdown

# Create your views here.

# def index(request):
#     articles = Article.objects.all()
#     dict = {'articles': articles}
#     return render(request, 'blog/index.html', dict)

class IndexView(ListView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'articles'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        context.update(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}

        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False

        page_number = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range

        if page_number == 1:
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page_number == total_pages:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data



# def article_page(request, article_id):
#     article = get_object_or_404(Article, pk = article_id)
#     article.increase_views()
#     article.content = markdown.markdown(article.content, extensions = [
#         'markdown.extensions.extra',
#         'markdown.extensions.codehilite',
#         'markdown.extensions.toc',
#     ])
#     form = CommentForm()
#     comment_list = article.comment_set.all()
#     dict = {'article': article, 'form': form, 'comment_list': comment_list}
#     return render(request, 'blog/single.html', dict)


class ArticlePageView(DetailView):
    model = Article
    template_name = 'blog/single.html'
    context_object_name = 'article'

    def get(self, request, *args, **kwargs):
        response = super(ArticlePageView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        article = super(ArticlePageView, self).get_object(queryset = None)
        md = markdown.Markdown(extensions = [
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify = slugify),
        ])
        article.content = md.convert(article.content)
        article.toc = md.toc
        return article

    def get_context_data(self, **kwargs):
        context = super(ArticlePageView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list,
        })
        return context




# def archives(request, year, month):
#     articles = Article.objects.filter(create_time__year = year, create_time__month = month)
#     dict = {'articles': articles}
#     return render(request, 'blog/index.html', dict)


class ArchiveView(ListView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'articles'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchiveView, self).get_queryset().filter(create_time__year = year, create_time__month = month)


# def category(request, pk):
#     cate = Category.objects.get(pk = pk)
#     articles = Article.objects.filter(category = cate)
#     dict = {'articles': articles}
#     return render(request, 'blog/index.html', dict)

class CategoryView(ListView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'articles'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk = self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category = cate)


class TagView(ListView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'articles'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk = self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags = tag)


def about_page(request):
    return render(request, 'blog/about.html')


def contact_page(request):
    return render(request, 'blog/contact.html')


def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = '请输入关键词'
        dict = {'error_msg': error_msg}
        return render(request, 'blog/index.html', dict)

    articles = Article.objects.filter(Q(title__icontains = q) | Q(content__icontains = q))
    dict = {'error_msg': error_msg, 'articles': articles}
    return render(request, 'blog/index.html', dict)







# def edit_page(request, article_id):
#     if article_id == 0:
#         return render(request, 'blog/edit_page.html')
#     else:
#         dict = {}
#         article = Article.objects.get(id = article_id)
#         dict['article'] = article
#         return render(request, 'blog/edit_page.html', dict)
#
#
# def edit_action(request):
#     id = request.POST.get('id')
#     title = request.POST.get('title')
#     content = request.POST.get('content')
#     if id == '0':
#         # 添加文章
#         article = Article(title = title, content = content)
#         article.save()
#         dict = {}
#         dict['article'] = article
#         return render(request,'blog/article_page.html', dict)
#     else:
#         # 更新文章
#         Article.objects.filter(id = id).update(title = title, content = content)
#         dict = {}
#         article = Article.objects.get(id = id)
#         dict['article'] = article
#         return render(request, 'blog/article_page.html', dict)

blog/templates/blog/about.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
		<link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
	    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

	    <!-- js -->
	    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
	    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
	    <script src="{% static 'blog/js/pace.min.js' %}"></script>
	    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="{% url 'blog:index' %}"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="博客">博客</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="联系">联系</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="../../static/blog/img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="{% url 'blog:index' %}">首页</a></li>
					<li><a href="{% url 'blog:index' %}">博客</a></li>
					<li><a href="{% url 'blog:about' %}">关于</a></li>
					<li><a href="{% url 'blog:contact' %}">联系</a></li>
				</ul>
			</nav>
		</div>

		<script src="../../static/blog/js/script.js"></script>
		
	</body>
</html>

blog/templates/blog/contact.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
		<link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
	    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

	    <!-- js -->
	    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
	    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
	    <script src="{% static 'blog/js/pace.min.js' %}"></script>
	    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="{% url 'blog:index' %}"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="博客">博客</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="联系">联系</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="{% url 'blog:index' %}">首页</a></li>
					<li><a href="{% url 'blog:index' %}">博客</a></li>
					<li><a href="{% url 'blog:about' %}">关于</a></li>
					<li><a href="{% url 'blog:contact' %}">联系</a></li>
				</ul>
			</nav>
		</div>

		<script src="../../static/blog/js/script.js"></script>
		
	</body>
</html>

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for article in articles %}
        <article class="post post-{{ article.id }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="{% url 'blog:category' article.category_id %}">{{ article.category }}</a></span>
                    {% for tag in article.tags.all %}
                        <span class="post-category"><a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a></span>
                    {% endfor %}
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ article.create_time }}">{{ article.create_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ article.author }}</a></span>
                    <span class="comments-link"><a href="{{ article.get_absolute_url }}#comment-list">{{ article.comment_set.count }} 评论</a></span>
                    <span class="views-count"><a href="{{ article.get_absolute_url }}">{{ article.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ article.summary }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ article.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
        {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}



{#    {% if is_paginated %}#}
{#        <div class="pagination-simple">#}
{#        {% if page_obj.has_previous %}#}
{#            <a href="?page={{ page_obj.previous_page_number }}">上一页</a>#}
{#        {% endif %}#}
{#        <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>#}
{#        {% if page_obj.has_next %}#}
{#            <a href="?page={{ page_obj.next_page_number }}">下一页</a>#}
{#        {% endif %}#}
{#        </div>#}
{#    {% endif %}#}


    {% if is_paginated %}
        <div class="pagination">
            {% if first %}
                <a href="?page=1">1</a>
            {% endif %}
            {% if left %}
                {% if left_has_more %}
                    <span>...</span>
                {% endif %}
                {% for i in left %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endfor %}
            {% endif %}
            <a href="?page={{ page_obj.number }}" style="color: blue">{{ page_obj.number }}</a>
            {% if right %}
                {% for i in right %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endfor %}
                {% if right_has_more %}
                    <span>...</span>
                {% endif %}
            {% endif %}
            {% if last %}
                <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
            {% endif %}
        </div>
    {% endif %}

{% endblock main %}

blog/templates/blog/single.html
{% extends 'base.html' %}

{% block main %}
    <article class="post post-{{ article.id }}">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="{% url 'blog:category' article.category_id %}">{{ article.category }}</a></span>
                {% for tag in article.tags.all %}
                    <span class="post-category"><a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a></span>
                {% endfor %}
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ article.create_time }}">{{ article.create_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ article.author }}</a></span>
                <span class="comments-link"><a href="{{ article.get_absolute_url }}#comment-list">{{ article.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="{{ article.get_absolute_url }}">{{ article.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ article.content|safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:article_comment' article.id %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">网址：</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel" id="comment-list">
            <h3>评论列表，共 <span>{{ article.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date" datetime="{{ comment.create_time }}">{{ comment.create_time }}</time>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                    </li>
                {% empty %}
                    暂无评论！
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}

{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ article.toc|safe }}
    </div>
{% endblock toc %}